#pragma once

#ifndef IBM_POWER_PC_ASM
#define IBM_POWER_PC_ASM

/* DIRECTIVE MACROS DECLARED FOR PROPRIATORY FUNCTIONS */
/* RELATIVE TO THE WII'S CPU */

/* THESE ARE TO ALLOCATE, DEALLOCATEE AND INVALIDATE DATA REQUESTS */
/* THROUGHOUT THE CPU */

#define DATA_CACHE_BLOCK_FLUSH(_VALUE) asm volatile("DCBF, 0 %0" :: ""(_VALUE))
#define INSTRUCTION_CACHE_BLOCK_INVALDATE(_VALUE) asm volatile("ICBI, 0 %0" :: ""(_VALUE))
#define DATA_CACHE_BLOCK_STORE(_VALUE) asm volatile("DCBS, 0 %0" :: ""(_VALUE))

#endif