#pragma once

#ifndef RACE_MANAGER
#define RACE_MANAGER

#include "common.h"
#include "player.h"

#ifndef RACE_TRACK
#define RACE_TRACK

typedef enum NITRO_TRACKS : U8
{
	LUIGI_CIRCUIT = 0x8,
	MOO_MOO_MEADOWS = 0x1,
	MUSHROOM_GORGE = 0x2,
	TOADS_FACTORY = 0x4,

	MARIO_CIRCUIT = 0x0,
	COCONUT_MALL = 0x5,
	DK_SUMMIT = 0x6,
	WARIO_GOLD_MINE = 0x7,

	DAISY_CIRCUIT = 0x9,
	KOOPA_CAPE = 0xF,
	MAPLE_TREEWAY = 0xB,
	GRUMBLE_VOLCANO = 0x3,

	DRY_DRY_RUINS = 0xE,
	MOONVIEW_HIGHWAY = 0xA,
	BOWSERS_CASTLE = 0xC,
	RAINBOW_ROAD = 0xD
};

typedef enum RETRO_TRACKS : U8
{
	GCN_PEACH_BEACH = 0x10,
	DS_YOSHI_FALLS = 0x14,
	SNES_GHOST_VALLEY_2 = 0x19,
	N64_MARIO_RACEWAY = 0x1A,
	
	N64_SHERBET_LAND = 0x1B,
	GBA_SHY_GUY_BEACH = 0x1F,
	DS_DELFINO_SQUARE = 0x17,
	GCN_WALUIGI_STADIUM = 0x12,

	DS_DESERT_HILLS = 0x15,
	GBA_BOWSER_CASTLE_3 = 0x1E,
	N64_DKS_JUNGLE_PARKWAY = 0x1D,
	GCN_MARIO_CIRCUUT = 0x11,

	SNES_MARIO_CIRCUIT_3 = 0x18,
	DS_PEACH_GARDENS = 0x16,
	GCN_DK_MOUNTAIN = 0x13,
	N64_BOWSERS_CASTLE = 0x1C
};

#endif

#define RACE_STRUCTURES

typedef struct COURSE_STATE;
typedef struct COURSE_CACHE
{
	const char* GET_CHARACTER_NAME(CHARACTER_ID CHARACTER_ID);
	static void INIT();
	static void LOAD(NITRO_TRACKS* NITRO, RETRO_TRACKS* RETRO);
	virtual ~COURSE_CACHE();
};

#ifndef RACE_PROPERTIES
#define RACE_PROPERTIES const

extern RACE_PROPERTIES NITRO_TRACKS NITRO[8];
extern RACE_PROPERTIES RETRO_TRACKS RETRO[4];
extern const S32 RANK_SCORE[5];
extern const U16 SCORE[4];

#endif

#endif
